# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        # dxf_files/ is intentionally not bundled — it's a runtime cache
        # populated by DXFLoader.sync_from_server() on first connection.
        ('qml', 'qml'),
        ('../shared', 'shared'),
    ],
    hiddenimports=[
        'shared',
        'shared.config_base',
        'shared.api_client_base',
        'shared.connection_worker',
        'shared.app_controller_base',
        'shared.dxf_preview_base',
        'shared.build_common',
        'requests',
        'PySide6.QtQuick',
        'PySide6.QtGui',
        'PySide6.QtQml',
        'src.config',
        'src.api_client',
        'src.database',
        'src.dxf_loader',
        'src.order_processor',
        'src.nesting_models',
        'src.nesting',
        'src.nesting.geometry',
        'src.nesting.placement',
        'src.nesting.optimizer',
        'src.nesting.pipeline',
        'src.enrichment',
        'src.dxf_output',
        'src.resources',
        'bridge',
        'bridge.app_controller',
        'bridge.refreshable_controller',
        'bridge.component_controller',
        'bridge.product_controller',
        'bridge.nesting_controller',
        'bridge.settings_controller',
        'bridge.replenishment_controller',
        'bridge.dxf_preview_item',
        'bridge.sheet_preview_item',
        'bridge.models',
        'bridge.models.component_model',
        'bridge.models.product_model',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Unfnest',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='App Icon/Unfnest.icns',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Unfnest',
)
import sys
if sys.platform == 'darwin':
    app = BUNDLE(
        coll,
        name='Unfnest.app',
        icon='App Icon/Unfnest.icns',
        bundle_identifier='com.unfnshed.unfnest',
    )
